package com.interactivedisplay.debug;

public enum DebugReason {
    MANAGER_NOT_READY,
    UNSUPPORTED_POSITION_MODE,
    WINDOW_DEFINITION_NOT_FOUND,
    SCHEMA_VALIDATION_FAILED,
    ENTITY_SPAWN_FAILED,
    NO_ACTIVE_WINDOW,
    INTERACTION_NOT_FOUND,
    OWNER_MISMATCH,
    CLICK_TYPE_MISMATCH,
    ACTION_TARGET_NOT_FOUND,
    ACTION_EXECUTION_FAILED
}
